### ISSUE TITLE
Ethernet question

### ISSUE THREAD

**Issue by under-score** [joshr120/PD-Stepper#10]
great device. Can I attach an ethernet/USB C adapter and use  incoming PTZ commands for motor movements?

**Comment by joshr120** [comment]
It may be technically possible but probably not very feasible. The ESP32 would need to act as USB host and you would need to write drivers for the specific USB-Ethernet chip.
You would also need some sort of UDB PD power injector to power the stepper driver at the same time.

**Comment by joshr120** [comment]
What does the "PD Status" show on the webserver?

**Comment by joshr120** [comment]
Looks like the motor driver is being disabled due to the PD voltage not being negotiated successfully. Are you using a USB C to C cable or an A to C cable?

**Comment by under-score** [comment]
A -> C (its an older version)
