### ISSUE TITLE
Suggestion to add caution for installation when not using heat spreader

### ISSUE THREAD

**Issue by jgueydan** [joshr120/PD-Stepper#11]
It might seem obvious to most, but you may want to add a caution in your Read Me description that if someone purchases the standard kit (without heat spreader) that they SHOULD use either spacers or other insulated material between the PD Stepper and the motor body to keep from shorting out the board.  Can't say enough about how much I love this board and it's endless possibilities for use!!  Very well done Josh!!  I'm not a programmer at all, so the included default firmware is great for testing and I very much appreciate it, plus the examples you provided in the software section.

**Comment by joshr120** [comment]
I am in the process of creating some more in depth assembly instructions so will be sure to include a note about it. Thanks for pointing it out.
