### ISSUE TITLE
Can you make a new Yaml using this custom component please

### ISSUE THREAD

**Issue by wshankles** [joshr120/PD-Stepper#13]
https://github.com/slimcdk/esphome-custom-components/tree/master/esphome/components/tmc2209

**Comment by joshr120** [comment]
This is being worked on should be released shortly

**Comment by joshr120** [comment]
New .yaml files have been added to the [ESPHome folder](https://github.com/joshr120/PD-Stepper/tree/main/Software/ESPHome) using the custom [TMC2209 component](https://github.com/slimcdk/esphome-custom-components/tree/master/esphome/components/tmc2209) thanks to @slimcdk

Let me know how you get on
