### ISSUE TITLE
What is the AUX connector?

### ISSUE THREAD

**Issue by pvince** [joshr120/PD-Stepper#16]
What type of connector is the AUX connector?

I was looking at adding a contact sensor and wanted to know what kind of crimper // connectors I will need to buy.

**Comment by joshr120** [comment]
The AUX connector is a 3 pin JST SH connector. Genuine crimpers can be quite expensive but plenty of places also sell pre-crimped leads: https://www.adafruit.com/product/5765

**Comment by pvince** [comment]
Thanks! Could you update the documentation somewhere with that information? (That it is a 3 pin JST SH connector)

**Comment by joshr120** [comment]
Will do!
