### ISSUE TITLE
proposed Altium sources and existing Kicad and EasyEDA sources

### ISSUE THREAD

**Issue by 001oc** [joshr120/PD-Stepper#7]
Now that pre-orders are starting to be shipped The Altium Source Files been added to the repo.

_Originally posted by @joshr120 in https://github.com/joshr120/PD-Stepper/issues/6#issuecomment-2406915418_

I can't see the altium files as of now and there is even no specific hint where to look specifically. Even most people will not have a Altium license. For that reason I will repost the Kicad and easyEDA sources to get people an easy way to work further on this project.

As @joshr120 stated the reason for not revealing the sources till now is not to be beaten in getting his project to market. That should be no problem now. For that reason it  shouldn't be neccessary to close the issue that fast because that will prevent others to get the information where to get sources - otherwise one could have the impression @joshr120 intention is to supress such information for an gpl-project.

Please let this issue open for now.

Kicad: https://github.com/user-attachments/files/17332545/PD-Stepper.zip

EasyEDA: https://oshwlab.com/adamscamden2/pd-stepper

**Comment by joshr120** [comment]
I committed the files but forgot to press push 🤦 my bad. The files can be found in the PCB folder. They are in Altium format as that is what the board was designed in. These can however be [converted to your PCB design software of choice.](https://refcircuit.com/articles/18-how-to-import-altium-designer-pcb-board-in-kicad.html) From my quick look at the easyeda design by @SoupySoups there were a couple of potential issue I spotted as well as not all features supported so I would recommend any future modifications are based off the fully tested files now that they are available.

I closed the previous issue as the original fully tested PCB files are now available so I considered it solved. Can keep this issue open for a while if you would like? The closed issues are still available for anyone to see.

**Comment by 001oc** [comment]
Thanks alot :-)

**Comment by SoupySoups** [comment]
> I committed the files but forgot to press push 🤦 my bad. The files can be found in the PCB folder. They are in Altium format as that is what the board was designed in. These can however be [converted to your PCB design software of choice.](https://refcircuit.com/articles/18-how-to-import-altium-designer-pcb-board-in-kicad.html) From my quick look at the easyeda design by @SoupySoups there were a couple of potential issue I spotted as well as not all features supported so I would recommend any future modifications are based off the fully tested files now that they are available.
> 
> I closed the previous issue as the original fully tested PCB files are now available so I considered it solved. Can keep this issue open for a while if you would like? The closed issues are still available for anyone to see.

Would you be willing to share such issues? From initial testing, all features that I chose to implement seem to be functioning correctly.

**Comment by joshr120** [comment]
Sure, I have not looked too in depth but here are couple of things I noticed that may affect performance. Other than the features you intentionally did not include the first thing I noticed was the setup of the current sensing resistors for the TMC2209. These carry the full motor current and currently your design does not have well defined return path from the resistors back to the IC. The GND pad on the TMC is not accessible on the top layer and the layers are only really stitched with the vias in the corner mounting holes. Adding a few GND vias near the GND pads of these resistors would help greatly.

Here is a screenshot from the TMC2209 datasheet which explains why it needs to be carefully considered:
![image](https://github.com/user-attachments/assets/a47f543b-b575-4b7f-83a2-dd5d8e5532de)

I would also probably want to increase the trace width between the current sense resistors and the TMC as these take the full motor current.

Decoupling caps for the various IC's as well as the VIN and VOUT caps for the 3.3V reg should be placed as close to the relevant pins as possible.

Hope these tips help with your future designs!

**Comment by SoupySoups** [comment]
> Sure, I have not looked too in depth but here are couple of things I noticed that may affect performance. Other than the features you intentionally did not include the first thing I noticed was the setup of the current sensing resistors for the TMC2209. These carry the full motor current and currently your design does not have well defined return path from the resistors back to the IC. The GND pad on the TMC is not accessible on the top layer and the layers are only really stitched with the vias in the corner mounting holes. Adding a few GND vias near the GND pads of these resistors would help greatly.
> 
> 
> 
> Here is a screenshot from the TMC2209 datasheet which explains why it needs to be carefully considered:
> 
> ![image](https://github.com/user-attachments/assets/a47f543b-b575-4b7f-83a2-dd5d8e5532de)
> 
> 
> 
> I would also probably want to increase the trace width between the current sense resistors and the TMC as these take the full motor current.
> 
> 
> 
> Decoupling caps for the various IC's as well as the VIN and VOUT caps for the 3.3V reg should be placed as close to the relevant pins as possible.
> 
> 
> 
> Hope these tips help with your future designs!

Oh yeah, that gnd section isnt very connected 😅
